services:
  musicshack:
    # image: ghcr.io/dimitrilapoudre/musicshack:latest
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - ${LIBRARY_PATH}:/downloads
      - musicshack_db:/data
    environment:
      HTTPS: ${HTTPS}
      LIBRARY_PATH: /downloads
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_PATH: /data
    restart: unless-stopped

volumes:
  musicshack_db:
