[project]
name = "MusicShack"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
DB_PATH = { description = "Database path", required = true }
DOWNLOAD_PATH = { description = "Download path", required = true }

ADMIN_DEFAULT_USERNAME = { description = "Admin default username", required = false }
ADMIN_DEFAULT_PASSWORD = { description = "Admin default password", required = false }

SESSION_COOKIE_NAME = { description = "Session cookie name", required = false }
SESSION_EXP = { description = "Session expiration duration", required = false }
SESSION_REMEMBER_EXP = { description = "Session remember expiration duration", required = false }

PORT = { description = "HTTP server port", required = false }
HTTPS = { description = "Enable HTTPS", required = false }

LOG_PRETTY = { description = "Pretty log output", required = false }
LOG_LEVEL = { description = "Log level", required = false }

DOWNLOAD_CONCURRENT = { description = "Concurrent downloads limit", required = false }

PLUGIN_PAGINATION_LIMIT = { description = "Plugin pagination limit", required = false }
PLUGIN_PAGINATION_OFFSET = { description = "Plugin pagination offset", required = false }
PLUGIN_CACHE_EXPIRATION = { description = "Plugin cache expiration duration", required = false }

GIN_MODE = { description = "Gin Mode", required = false, default = "release"}

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
